// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvmocewcwyntnqtkcure.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bW9jZXdjd3ludG5xdGtjdXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNjE3MDksImV4cCI6MjA0OTkzNzcwOX0.8mveyK-TMKfdpmJ2gXfM4K5YRj2v8r1E4Br2tJGorik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);